include:
  - project: 'common/gitlab-ci-common'
    file: '/templates/.github-release.yml'
  - project: 'common/gitlab-ci-common'
    file: '/templates/.pypi-release.yml'

stages:
  - linters
  - release
  - global

variables:
  PYTHON_IMAGE: builder.local:18080/common/base_images/python39:23e82f3e
  POETRY_REPOSITORIES_PYPI: http://builder.local:8081/repository/pypi_all/simple/

.poetry_install:
  image: $PYTHON_IMAGE
  before_script:
    - pip install poetry==1.2.2
    - poetry config virtualenvs.create false
    # - poetry config repositories.mirror http://192.168.1.106:8081/repository/pypi_all/simple/ --local
    - poetry config repositories.pypi http://builder.local:8081/repository/pypi_all/simple/
    - poetry install


Check author name and email:
  image: $PYTHON_IMAGE
  stage: linters
  script:
    - export BAD_AUTHOR_LINES=$(git log --pretty=format:"%h %ce %ae %cn %an" | grep -v 'aks@smartleks aks@smartleks aks aks' | wc -l)
    - echo ${BAD_AUTHOR_LINES}
    - if [ ${BAD_AUTHOR_LINES} -ne 0 ]; then exit 1; fi

Run tests:
  extends: .poetry_install
  stage: linters
  script:
    - python -m pytest tests/
  except:
    - tags
    - master

Build package:
  extends: .poetry_install
  stage: linters
  script:
    - poetry build
  except:
    - tags
    - master

Release:
  extends: .poetry_install
  stage: release
  script:
    - poetry version $(echo ${CI_COMMIT_TAG} | cut -d '-' -f2)
    - poetry build
    - poetry config repositories.pypi_local "$pypi_url_local"
    - poetry publish -r pypi_local -u "$pypi_local_user" -p "$pypi_local_pwd"
    - poetry publish -u "$pypi_global_user" -p "$pypi_global_pwd" --dry-run
  only:
    - /^release-[0-9]+\.[0-9]+\.[0-9]+$/

GLOBAL GITHUB (public release):
  stage: global
  image: $PYTHON_IMAGE
  variables:
    GITHUB_PROJECT_URL: git@github.com:smartleks/little-conf.git
  extends:
    - .github_release_master
  only:
    - /^release-[0-9]+\.[0-9]+\.[0-9]+$/
  when: manual

GLOBAL PYPI (public release):
  stage: global
  extends:
    - .poetry_install
    - .pypi_release_poetry
  only:
    - /^release-[0-9]+\.[0-9]+\.[0-9]+$/
  when: manual
